export const CONFIG_OPTIONS = 'CONFIG_OPTIONS';
export const EMAIL_HOST = 'EMAIL_HOST';
export const EMAIL_PORT = 'EMAIL_PORT';
export const EMAIL_USERNAME = 'EMAIL_USERNAME';
export const EMAIL_PASSWORD = 'EMAIL_PASSWORD';
export const EMAIL_FROM_NAME = 'EMAIL_FROM_NAME';
export const EMAIL_FROM_ADDRESS = 'EMAIL_FROM_ADDRESS';
